# -*- coding: utf-8 -*-
"""Fatima_Fellowship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18CjqtC1M38XSkFGFWvWulQxfBc27FNbH

# Tiny-Aya Base Model Testing Notebook

TinyAya-Base, a pretrained 3.35B-parameter model: TinyAya-Base covers 70+ languages*, including many lower-resourced languages from around the globe.
[blog source](https://cohere.com/blog/cohere-labs-tiny-aya)

## Setup and Installation
"""

!pip install -q transformers accelerate torch huggingface_hub

"""### Log in to HuggingFace account"""

from huggingface_hub import notebook_login
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


notebook_login()

import os
from google.colab import userdata


HF_TOKEN = userdata.get('HF_TOKEN')
os.environ["HF_TOKEN"] = HF_TOKEN

"""### Model Loading and Tokenizer"""

MODEL_NAME = "CohereLabs/tiny-aya-base"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME,device_map="auto")

print(f"Model loaded! Device: {model.device}")
print(f"Parameters: {model.num_parameters() / 1e9:.2f}B")

"""### Helper Function"""

def gen_res(prompt, max_new_tokens=128, temperature=0.1, top_p=0.95,top_k=50):

    inputs = tokenizer( prompt,return_tensors="pt").to(model.device)

    gen_tokens = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=True,
            temperature=temperature,
            top_p=top_p,
            top_k = 50
        )

    input_len = inputs["input_ids"].shape[-1]
    res = tokenizer.decode(gen_tokens[0][input_len:], skip_special_tokens=True)
    return res

"""#### Test"""

# input prompt
prompt = "The capital of Spain is"
# LLM's output
res = gen_res(prompt,top_k=1)
print(prompt) # display input prompt
print(res) # display LLM's output

"""### Arithmetic

❌ Mistake

- right answer : `$13.7`
"""

prompt = "If you buy 3 apples for $6.3 each and pay with $20, how much change do you get?"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake


- right answer : `$2.42`
"""

prompt = "If you buy 3 apples for $7.26, how much does one apple cost?"
res = gen_res(prompt)
print(prompt)
print(res)

"""✅ Right answer example"""

# @title
# { display-mode: "form" }

prompt = "All cats are animals. Some animals are black. Can we conclude that some cats are black?"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Hallucination / Logical Error

❌ Mistake

- right answer : cannot be determined
"""

prompt = "Tom is bigger than Jack. Peter is smaller than Jack. What is the age of Jack ?"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Fact Check

Has Basic knowledge but can be easily deceived by misleading prompts + wrong factual check

✅ Right answer examples
"""

# @title
#{display-mode:form}
prompt = "Who was the first president of Madagascar?"
res = gen_res(prompt)
print(prompt)
print(res)

# @title
#{display-mode:form}
prompt = "Qui etait le tout premier president de la Republique de Madagascar?"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake
 - possible right answers : 1) you can watch the Penguins of Madagascar movie on xxx platform , 2) there are no penguins in Madagascar
"""

prompt = "Where do we see the penguins of Madagascar?"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake
 - right answer : Madagascar does not share land border with any country
"""

prompt = "Name two countries that share land borders with Madagascar"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake
 - right answer : Brazil
"""

prompt = "Name a Latin American country that does not speak Spanish"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Context understanding

❌ Mistake
 - right answer : Peter
"""

prompt = "Peter told Jack that he would help him with the project after he finished his homework. Who needs to finish their homework first?"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Instructions in High resource Language

❌ Mistake

- possible right answer : ["Nigeria", "South Africa", "Egypt", "Algeria"]
"""

prompt = "List 4 African countries in valid JSON array format,and output nothing else"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake

- possible right answer : ["Nigeria", "Afrique du Sudy", "Egypte", "Algerie"]
"""

prompt = "Liste 4 pays africains en format JSON et n'affiche rien d'autres"
res = gen_res(prompt,max_new_tokens=512)
print(prompt)
print(res)

"""✅ Right answer example in Englsih"""

# @title
#{display-mode:form}
prompt = "Name an African country that was not colonized"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake in French

- right answer : Ethiopie
"""

prompt = "Nomme un pays Africain qui n'a jamais été colonisé"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Low-resource Language

✅ Right answer example in High resource Language
"""

# @title
#{display-mode:form}
prompt = "If you drop an egg on a rock, what is the most likely outcome and why?"
res = gen_res(prompt)
print(prompt)
print(res)

# @title
#{display-mode:form}
prompt = "Si un oeuf tombe sur un rocher, qu'est ce qui pourrait se passer?"
res = gen_res(prompt)
print(prompt)
print(res)

# @title
#{display-mode:form}
prompt = "Peter kept checking their phone during Marta's presentation. What might be two possible reasons for that?"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake

- right answer : vaky ny atody raha milatsaka ambony vato
"""

prompt = "Raha milatsaka ambony vato ny atody dia inona no mety hitranga ?"
res = gen_res(prompt)
print(prompt)
print(res)

"""❌ Mistake

- right answer : I love you
"""

prompt = "Adikao amin'ny anglisy ny hoe Tiako ianao"
res = gen_res(prompt)
print(prompt)
print(res)

"""### Contradictory Instruction

❌ Mistake

- right answer : impossible,contradictory instruction
"""

prompt = "Reply with only the word YES and do not use any other words and explain why your answer is correct in two sentences."
res = gen_res(prompt)
print(prompt)
print(res)